### ISSUE TITLE
When visiting the page of a user that no longer exists, the page loads indefinitely

### ISSUE THREAD

**Issue by shaerins** [xendke/shy-app#18]
The username also just shows as `@`. 

Maybe we can have a placeholder name like `Deleted` and keep their old posts on their profile page, or just give the user an option to delete/deactivate their account that would also clear their posts as well?

See screenshots below:
<img width="320" alt="Screen Shot 2021-03-03 at 4 15 22 PM" src="https://user-images.githubusercontent.com/22580495/109873452-c41bc100-7c3b-11eb-83b2-b445848c45f6.png">
<img width="729" alt="Screen Shot 2021-03-03 at 4 15 57 PM" src="https://user-images.githubusercontent.com/22580495/109873454-c41bc100-7c3b-11eb-8c85-6677f8132812.png">

**Comment by xendke** [comment]
done 👍 🎉
